parameters:
#    tudor_blog.example.class: Tudor\BlogBundle\Example

services:
#    tudor_blog.example:
#        class: %tudor_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
